import { Plus_Jakarta_Sans } from 'next/font/google'
import Header from './_components/header'
import './globals.css'
import { Providers } from './_redux/provider'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <Header />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
